name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: new_password
          MYSQL_DATABASE: MyData
          MYSQL_ROOT_PASSWORD: new_password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v1

      - name: Verify MariaDB connection
        env:
          PORT: "192.168.64.9:3306"
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done          

      - name: Test
        run: |
                    your tests
